### PR TITLE
Client side delete

### PR DESCRIPTION
**Pull request by hjdivad**

### CODE REVIEW

**Comment by hjdivad** [comment]
@workmanw you'll notice the error manifests on this pr but not if you `yarn link` to https://github.com/emberjs/data/pull/5249

**Comment by workmanw** [comment]
Hey @hjdivad Thanks for this! I'm going to take what you've got and add a commit on top to create a second button for this so we can demo both behaviors.

**Comment by hjdivad** [comment]
@workmanw 👍 

Although we're going to land a fix to get the semantics of `unloadRecord` for *sync* relationships back to client-side delete so you won't need to do this.

In either case, having an adapter-enabled client side delete is definitely public API and should work.

**Comment by workmanw** [comment]
@hjdivad Is there a PR for that I can track? It's not https://github.com/emberjs/data/pull/5249 right? No problem if it's not yet started. I'm just trying to make sure I'm following along.

**Comment by hjdivad** [comment]
@workmanw i'm going to merge that PR; the only thing I'll do before merging is trace the local delete case to confirm that the case is actually covered as @runspired believes.

I'll open a new pr for restoring the semantics completely (this work was partially done earlier).  When I do I'll tag https://github.com/emberjs/data/issues/5136 so you should get notified if you're following that issue.

**Comment by hjdivad** [comment]
@workmanw i'm going to merge that PR; the only thing I'll do before merging is trace the local delete case to confirm that the case is actually covered as @runspired believes.

I'll open a new pr for restoring the semantics completely (this work was partially done earlier).  When I do I'll tag https://github.com/emberjs/data/issues/5136 so you should get notified if you're following that issue.

**Comment by workmanw** [comment]
👍  Thanks a lot.

**Pull request merged**
